- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  #$ sudo apt install software-properties-common
  #$ sudo apt-add-repository --yes --update ppa:ansible/ansible
  #$ sudo apt install ansible
  #$ ansible-playbook <this_playbook> --ask-become-pass

  #To install dependencies specify the mode
  # ansible-playbook <this_playbook> --ask-become-pass -e "mode=[VSMF/NSMF/VSMF+NSMF]"

  #To start also the slicer
  # ansible-playbook <this_playbook> --ask-become-pass -e "mode=[VSMF/NSMF/VSMF+NSMF] start=true"

  #To only start the slicer
  # ansible-playbook <this_playbook> --ask-become-pass -e "start=true config=<path>"

  - name: check mode
    debug:
      msg: "Accepted modes: [VSMF, NSMF, VSMF+NSMF]. Passed: {{ mode }}"
    when: mode is defined and not (mode == "VSMF" or mode != "NSMF" or mode != "VSMF+NSMF")

  - meta: end_play
    when: mode is defined and not (mode == "VSMF" or mode != "NSMF" or mode != "VSMF+NSMF")

  - include: dependencies-task.yml
    when: mode is defined or start is defined

  - include: vsmf-task.yml
    when: mode is defined and mode == "VSMF"

  - include: nsmf-task.yml
    when: mode is defined and mode == "NSMF"

  - include: total-task.yml
    when: mode is defined and mode == "VSMF+NSMF"

  #start
  - name: start rabbitmq
    shell: service rabbitmq-server start || true
    become: yes
    when: start is defined and start == "true"

  - name: start postgresql
    shell: service postgresql start || true
    become: yes
    when: start is defined and start == "true"

  - name: start postgresql
    shell: psql -c "ALTER USER postgres PASSWORD 'postgres';" && psql -c "CREATE DATABASE timeo;" 2>/dev/null
    become: yes
    become_user: postgres
    when: start is defined and start == "true"
  
  - name: get current working directory
    shell: echo $(pwd)
    register: current_pwd

  - name: start VS in VSFM only mode
    shell: cd {{ current_pwd.stdout }}/slicer/slicer/SEBASTIAN/VSMF_APP/target/ && echo finisci_il_path
    when: mode is defined and mode == "VSMF"

  - name: start VS in NSFM only mode
    shell: cd {{ current_pwd.stdout }}/slicer/slicer/SEBASTIAN/NSMF_APP/target/ && echo finisci_il_path
    when: mode is defined and mode == "NSMF"

  - name: start VS in VSFM+NSMF mode
    shell: cd {{ current_pwd.stdout }}/slicer/slicer/SEBASTIAN/SEBASTIAN_CORE/target/ && echo finisci_il_path
    when: mode is defined and mode == "VSMF+NSMF"

